# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_mycourses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mycourses',
            options={'verbose_name': 'My Courses', 'verbose_name_plural': 'My Courses'},
        ),
        migrations.AlterField(
            model_name='mycourses',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='owned', to='courses.Course'),
        ),
    ]
