# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('courses', '0016_auto_20170807_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='secondary',
            field=models.ManyToManyField(blank=True, null=True, related_name='secondary_category', to='categories.Categories'),
        ),
    ]
