# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_course_secondary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='secondary',
            field=models.ManyToManyField(blank=True, related_name='secondary_category', to='categories.Categories'),
        ),
    ]
